/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JefeDpto;
 
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JOptionPane;
/**
 *
 * @author oliver
 */
public class JefeDpto_interfaz extends javax.swing.JFrame { /**
     * Creates new form JefeDpto_interfaz
     */
    SolicitudRegistros pantallaRegistrosSolicitud;
    SolicitudNueva pantallaNuevaSolicitud;
    boolean actualizarTabla=false;
    int idUsuario;
    public JefeDpto_interfaz(int idUsuario) {
       
        initComponents();      
              this.idUsuario=idUsuario;
               this.pantallaNuevaSolicitud = new SolicitudNueva(idUsuario);

         this.pantallaNuevaSolicitud = new SolicitudNueva(idUsuario);
        pantallaNuevaSolicitud.setVisible(true);
        tbNuevaSolicitud.add("Nueva Solicitud",pantallaNuevaSolicitud);  
        
        pantallaRegistrosSolicitud= new SolicitudRegistros(idUsuario);
        pantallaRegistrosSolicitud.setVisible(true);
        tbNuevaSolicitud.add("Solicitudes Elaboradas",pantallaRegistrosSolicitud);  
        
        pantallaNuevaSolicitud.btnEnviar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent arg0) {
               actualizarTabla=true;
            }
        });
       
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        tbNuevaSolicitud = new javax.swing.JTabbedPane();
        btnCerrarSesion = new javax.swing.JButton();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modulo De Jefe De Departamento");
        setAlwaysOnTop(true);

        tbNuevaSolicitud.setPreferredSize(new java.awt.Dimension(820, 495));
        tbNuevaSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNuevaSolicitudMouseClicked(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbNuevaSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbNuevaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbNuevaSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNuevaSolicitudMouseClicked
       if(tbNuevaSolicitud.getSelectedIndex()==1)
       {
           if(actualizarTabla)
           {
             pantallaRegistrosSolicitud.traerSolicitudes("Solicitada");  
           }
           actualizarTabla=false;
       }
    }//GEN-LAST:event_tbNuevaSolicitudMouseClicked

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed

     this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed
     /**
     * @param args the command line arguments
     */
    
    public void listen()
    {
        JOptionPane.showMessageDialog(null,"ha cambiado algo");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JefeDpto_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JefeDpto_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JefeDpto_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JefeDpto_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JefeDpto_interfaz().setVisible(true);
            }
        });
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private java.awt.Label label1;
    private javax.swing.JTabbedPane tbNuevaSolicitud;
    // End of variables declaration//GEN-END:variables

//    private DefaultListModel<String> busquedaListaResponsables(String CadenaTxtResponsable, DefaultListModel<String> modeloResponsables) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
}
