/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JefeDpto;

import Solicitud.Solicitud_controlador;
import Usuarios.usuarios_controlador;
import Vehiculos.vehiculos_controlador;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author fernando
 */
public class ModificarSolicitud extends javax.swing.JPanel {
DefaultListModel <String> modeloResponsables=new DefaultListModel <>();
 DefaultListModel <String> modeloVehiculos=new DefaultListModel <>();
 String arregloResponsables[][];
 String arregloVehiculos[][];
 int idResponsable=0;
 int idVehiculo=0;
 String lugar="";
 String actividad="";
 String dias="";
 String responsable="";
 String vehiculo="";
 String pernoctado="";
 String fecha="";
 boolean modificandoSol=false;
 String idFolio;
    /**
     * Creates new form ModificarSolicitud
     */
    public ModificarSolicitud() {
        initComponents();
        listaEncargado.setVisible(false);
       listaVehiculo.setVisible(false);
       cargaElementosListaResponsables();
       cargarElementosListaVehiculo();
       ButtonGroup bG = new ButtonGroup();
       bG.add(rbPernoctado);
       bG.add(rbNoPernoctado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloSol = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtActividad = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEncargado = new javax.swing.JList<>();
        txtResponsable = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaVehiculo = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        txtVehiculo = new javax.swing.JTextField();
        rbPernoctado = new javax.swing.JRadioButton();
        rbNoPernoctado = new javax.swing.JRadioButton();
        btnEnviar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        txtFechaSalida = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtDias = new javax.swing.JSpinner();

        lblTituloSol.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTituloSol.setText("Ingresa una nueva solicitud");

        jLabel3.setText("Lugar");

        jLabel4.setText("Actividad");

        txtActividad.setColumns(20);
        txtActividad.setRows(5);
        jScrollPane1.setViewportView(txtActividad);

        jLabel5.setText("Responsable");

        listaEncargado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaEncargado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaEncargadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaEncargado);

        txtResponsable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtResponsableKeyReleased(evt);
            }
        });

        listaVehiculo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaVehiculoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaVehiculo);

        jLabel6.setText("Vehiculo");

        txtVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVehiculoKeyReleased(evt);
            }
        });

        rbPernoctado.setSelected(true);
        rbPernoctado.setText("Pernoctado");

        rbNoPernoctado.setText("No pernoctado");

        btnEnviar.setText("Actualizar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha de salida");

        btnLimpiar.setText("Cancelar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel8.setText("Duracion en dias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTituloSol)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEnviar)
                                .addGap(23, 23, 23)
                                .addComponent(btnLimpiar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDias, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addGap(430, 430, 430))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbPernoctado)
                                        .addGap(29, 29, 29)
                                        .addComponent(rbNoPernoctado)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTituloSol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPernoctado)
                            .addComponent(rbNoPernoctado)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    
     public void cargarCamposModificar(String lugar,String actividad,String dias,String responsable
    ,String vehiculo,String pernoctado,String idFolio,String fecha,int idVehiculo)
    {
                txtLugar.setText(lugar);
                txtActividad.setText(actividad);
                txtDias.setValue(Integer.parseInt(dias));
                txtResponsable.setText(responsable);
                txtVehiculo.setText(vehiculo);
                rbPernoctado.setSelected(pernoctado.equals("si"));
                rbNoPernoctado.setSelected(pernoctado.equals("no"));
                lblTituloSol.setText("Modifica la solicitud (Folio "+idFolio+")");
                this.idFolio=idFolio;
                this.idVehiculo=idVehiculo;
                try {
            
                        String[] fechaSplit=fecha.split("/");
                        String fechaSalida=fechaSplit[1]+"/"+fechaSplit[0]+"/"+fechaSplit[2];
            
                        java.text.SimpleDateFormat formato = new java.text.SimpleDateFormat("dd/MM/yyyy");
                        java.util.Date fechaDate = formato.parse(fechaSalida);
                        txtFechaSalida.setDate(fechaDate);
            
                    } catch (Exception ex) {
                        Logger.getLogger(JefeDpto_interfaz.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }
    public void limpiarCampos()
    {
        txtLugar.setText("");
        txtActividad.setText("");
        txtDias.setValue(Integer.parseInt("0"));
        txtResponsable.setText("");
        txtVehiculo.setText("");
        rbPernoctado.setSelected(true);
        rbNoPernoctado.setSelected(false);
    }
    
    public void cargaElementosListaResponsables()
    {
        usuarios_controlador objUsuario=new usuarios_controlador();
        arregloResponsables=objUsuario.traerUsuarioTipoEmpleado();
        for(int i=0;i<arregloResponsables.length;i++)
        {
            
            modeloResponsables.addElement(arregloResponsables[i][0]);
        }
       listaEncargado.setModel(modeloResponsables);
    }
    
    public void cargarElementosListaVehiculo()
    {
       vehiculos_controlador objVehiculos= new vehiculos_controlador();
       arregloVehiculos=objVehiculos.traerProductoTipoVehiculo();
        for(int i=0;i<arregloVehiculos.length;i++)
        {
         modeloVehiculos.addElement(arregloVehiculos[i][0]);
        }
       listaVehiculo.setModel(modeloVehiculos);
    }
    
  public DefaultListModel<String> busquedaLista(String cadenaEntrada,DefaultListModel<String> modelo)
   {
     DefaultListModel<String> resultadosBusqueda=new DefaultListModel<String>();
     String elementoModelo="";
     
     for(int i=0;i<modelo.size();i++)
     {  
         elementoModelo=modelo.get(i);
         if(elementoModelo.contains(cadenaEntrada))
         {
           resultadosBusqueda.addElement(modelo.get(i));
         }
     }
     
     return resultadosBusqueda;
   }
                     
    
    private void listaEncargadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaEncargadoMouseClicked
        String valorSeleccionado=listaEncargado.getSelectedValue();
        for(int i=0;i<arregloResponsables.length;i++)
        {
            if(valorSeleccionado.equals(arregloResponsables[i][0]))
            {
                idResponsable=Integer.parseInt(arregloResponsables[i][1]);
            }
        }
        listaEncargado.setVisible(false);
        txtResponsable.setText(valorSeleccionado);
    }//GEN-LAST:event_listaEncargadoMouseClicked

    private void txtResponsableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResponsableKeyReleased
        String CadenaTxtResponsable=txtResponsable.getText();
        DefaultListModel<String> resultadosBusqueda=new DefaultListModel<String>();
        if(CadenaTxtResponsable.matches("[a-zA-Z]+"))
        {

            resultadosBusqueda=busquedaLista(CadenaTxtResponsable,modeloResponsables);
            listaEncargado.setModel(resultadosBusqueda);
            listaEncargado.setVisible(true);
        }
        else
        {
            listaEncargado.setModel(modeloResponsables);
            listaEncargado.setVisible(false);
        }
    }//GEN-LAST:event_txtResponsableKeyReleased

    private void listaVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaVehiculoMouseClicked
        String valorSeleccionado=listaVehiculo.getSelectedValue();
        for(int i=0;i<arregloVehiculos.length;i++)
        {
            if(valorSeleccionado.equals(arregloVehiculos[i][0]))
            {
                idVehiculo=Integer.parseInt(arregloVehiculos[i][1]);
            }
        }
        listaVehiculo.setVisible(false);
        txtVehiculo.setText(valorSeleccionado);
    }//GEN-LAST:event_listaVehiculoMouseClicked

    private void txtVehiculoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehiculoKeyReleased
        String CadenaTxtVehiculo = txtVehiculo.getText();
        DefaultListModel<String> resultadosBusqueda=new  DefaultListModel<String>();
        if(CadenaTxtVehiculo.matches("[a-zA-Z]+"))
        {
            resultadosBusqueda = busquedaLista(CadenaTxtVehiculo, modeloVehiculos);
            listaVehiculo.setModel(resultadosBusqueda);
            listaVehiculo.setVisible(true);
        }
        else
        {
            listaVehiculo.setModel(modeloVehiculos);
            listaVehiculo.setVisible(false);
        }
    }//GEN-LAST:event_txtVehiculoKeyReleased

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String pernoctado="";
        String lugar=txtLugar.getText();
        Date fechaSalida= txtFechaSalida.getDate();
        String actividad=txtActividad.getText();
        String personalViatico=txtResponsable.getText();
        String statusViatico="Solicitado";
        int idUsuarioJefeDpto=1;
        int diasDuracion=(Integer)txtDias.getValue();

        Solicitud_controlador objetoSolicitud=new Solicitud_controlador();

        if(rbPernoctado.isSelected())
        {
            pernoctado="si";
        }

        else if(rbNoPernoctado.isSelected())
        {
            pernoctado="no";
        }
        
         if(lugar.equals("")||actividad.equals("")||personalViatico.equals(""))
            {
                JOptionPane.showMessageDialog(null,"Los campos no deben estar vacios");
            }
         
         else
         {
            objetoSolicitud.modificaSolicitud(Integer.parseInt(idFolio),fechaSalida,personalViatico,diasDuracion,lugar,actividad,pernoctado,statusViatico,idUsuarioJefeDpto,idVehiculo);
            limpiarCampos();
         }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEnviar;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTituloSol;
    private javax.swing.JList<String> listaEncargado;
    private javax.swing.JList<String> listaVehiculo;
    private javax.swing.JRadioButton rbNoPernoctado;
    private javax.swing.JRadioButton rbPernoctado;
    private javax.swing.JTextArea txtActividad;
    private javax.swing.JSpinner txtDias;
    private com.toedter.calendar.JDateChooser txtFechaSalida;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtResponsable;
    private javax.swing.JTextField txtVehiculo;
    // End of variables declaration//GEN-END:variables
}
