
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author franciscoemanuelcardenasramos
 */
public class AsigPrivi extends javax.swing.JFrame {

   Usuarios pr = new Usuarios();
     conectar cc = new conectar();
    Connection cn = cc.conexion();
    /**
     * Creates new form AsigPrivi
     */
    public AsigPrivi() {
        initComponents();
        mostrartipousuario();
        mostrarModulo();
    }

    
    
  
    
     void mostrartipousuario(){
    
    DefaultComboBoxModel modelo = new DefaultComboBoxModel();  
           try {
            Statement statement = cn.createStatement();
            ResultSet obtenerAlmacen = statement.executeQuery("SELECT Nombre_TipoUsr FROM Tipo_Usr   where idTipo_Usr < 4");
            while (obtenerAlmacen.next()) {
              tipousuario.addItem(obtenerAlmacen.getString(1));
            }//FIN WHILE
        }catch (SQLException ex) {
            Logger.getLogger(InterfazProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    
     void mostrarModulo(){
    
    DefaultComboBoxModel modelo = new DefaultComboBoxModel();  
           try {
            Statement statement = cn.createStatement();
            ResultSet obtenermodulo = statement.executeQuery("SELECT Nombre_Mod FROM Modulo ");
            while (obtenermodulo.next()) {
              modulo.addItem(obtenermodulo.getString(1));
            }//FIN WHILE
        }catch (SQLException ex) {
            Logger.getLogger(InterfazProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    
    public int obtenerIdTipousuario(JComboBox tipousuario/**/){
    int resultado=0;
    String valor= tipousuario.getSelectedItem().toString();
    
    try {
            
            Statement statement = cn.createStatement();
            ResultSet obtenerIdTipousuario = statement.executeQuery("SELECT idTipo_Usr FROM almacen where Nombre_TipoUsr='"+valor+"'");
            while (obtenerIdTipousuario.next()) {
                resultado=obtenerIdTipousuario.getInt(1);
            }//FIN WHILE
            
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    return resultado;
}  
    
     public int obtenerIdmodulo(JComboBox modulo/**/){
    int resultado=0;
    String valor= modulo.getSelectedItem().toString();
    
    try {
            
            Statement statement = cn.createStatement();
            ResultSet obtenerIdmodulo = statement.executeQuery("SELECT idModulo FROM almacen where Nombre_Mod='"+valor+"'");
            while (obtenerIdmodulo.next()) {
                resultado=obtenerIdmodulo.getInt(1);
            }//FIN WHILE
            
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    return resultado;
}  
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tipousuario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        agregar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        borrar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        actualizar = new javax.swing.JComboBox<>();
        ver = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        modulo = new javax.swing.JComboBox<>();

        jLabel6.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistema de control de viaticos y vehícuar");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banner.png"))); // NOI18N

        jLabel7.setText("Tipo de usuario");

        tipousuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar  tipo de usuario" }));
        tipousuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipousuarioMouseClicked(evt);
            }
        });
        tipousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipousuarioActionPerformed(evt);
            }
        });

        jButton1.setText("Asignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Agregar");

        agregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Permitido", "Permitido" }));

        jLabel3.setText("Borrar");

        borrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Permitido", "Permitido" }));

        jLabel4.setText("Actualizar");

        jLabel5.setText("Vizualizar");

        actualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Permitido", "Permitido" }));

        ver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Permitido", "Permitido" }));

        jLabel8.setText("Modulo");

        modulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Modulo" }));
        modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton2)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipousuario, 0, 263, Short.MAX_VALUE)
                            .addComponent(agregar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(borrar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(actualizar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(8, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(modulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(86, 86, 86))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(266, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(258, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int obtenerIdTipoUsr(JComboBox cmbAlmacen/**/){
    int resultado=0;
    String valor= tipousuario.getSelectedItem().toString();
    
    try {
        
            Statement statement = cn.createStatement();
            ResultSet obtenerIdTipoUsr= statement.executeQuery("SELECT idTipo_Usr FROM `Tipo_Usr` WHERE Nombre_TipoUsr = '"+ valor+"'");
            while (obtenerIdTipoUsr.next()) {
                resultado=obtenerIdTipoUsr.getInt(1);
            }//FIN WHILE
            
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    return resultado;
}
     
    
    public int obtenerIdModulo(JComboBox cmbmodulo/**/){
    int resultado=0;
    String valor= modulo.getSelectedItem().toString();
    
    try {
        
            Statement statement = cn.createStatement();
            ResultSet obtenerIdModulo= statement.executeQuery("SELECT idModulo FROM Modulo WHERE Nombre_Mod = '"+ valor+"'");
            while (obtenerIdModulo.next()) {
                resultado=obtenerIdModulo.getInt(1);
            }//FIN WHILE
            
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    return resultado;
}
   
    
    
    
    //Lo sacar las S o N
    public String obtenerAP(JComboBox cmbEstado,JComboBox cmbEstado2){
    String resultado="";
    int valor= obtenerIdTipoUsr(tipousuario);
    int valor2=obtenerIdModulo(modulo);
    
    try {
            
            Statement statement = cn.createStatement();
            ResultSet obtenerAP = statement.executeQuery(" SELECT Agregar_Priv FROM Privilegios INNER JOIN Tipo_Usr on Privilegios.Tipo_Usr_idTipo_Usr = Tipo_Usr.idTipo_Usr where Tipo_Usr_idTipo_Usr = '"+valor+"' and Modulo_idModulo= '"+valor2+"'  ");
            while (obtenerAP.next()) {
                resultado=obtenerAP.getString(1);
            }//FIN WHILE
            
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    return resultado;
    }
    
    


    
    
    //" SELECT Agregar_Priv,Borrar_Priv,Actualizar_Priv ,Visualizar_Priv FROM Privilegios INNER JOIN Tipo_Usr on Privilegios.Tipo_Usr_idTipo_Usr = Tipo_Usr.idTipo_Usr where Tipo_Usr_idTipo_Usr = '"+valor+"'   "
     public String obtenerBP(JComboBox cmbEstado,JComboBox cmbEstado2){
    String resultado="";
  int valor= obtenerIdTipoUsr(tipousuario);
   int valor2=obtenerIdModulo(modulo);
    
    try {
            
            Statement statement = cn.createStatement();
            ResultSet obtenerAP = statement.executeQuery(" SELECT Borrar_Priv FROM Privilegios INNER JOIN Tipo_Usr on Privilegios.Tipo_Usr_idTipo_Usr = Tipo_Usr.idTipo_Usr where Tipo_Usr_idTipo_Usr = '"+valor+"' and Modulo_idModulo= '"+valor2+"'  ");
            while (obtenerAP.next()) {
                resultado=obtenerAP.getString(1);
            }//FIN WHILE
            
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    return resultado;
}
     
     
     public String obtenerAcP(JComboBox cmbEstado,JComboBox cmbEstado2){
    String resultado="";
     int valor= obtenerIdTipoUsr(tipousuario);
      int valor2=obtenerIdModulo(modulo);
    
    try {
            
            Statement statement = cn.createStatement();
            ResultSet obtenerAP = statement.executeQuery(" SELECT Actualizar_Priv FROM Privilegios INNER JOIN Tipo_Usr on Privilegios.Tipo_Usr_idTipo_Usr = Tipo_Usr.idTipo_Usr where Tipo_Usr_idTipo_Usr = '"+valor+"' and Modulo_idModulo= '"+valor2+"'  ");
            while (obtenerAP.next()) {
                resultado=obtenerAP.getString(1);
            }//FIN WHILE
            
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    return resultado;
}
    
     
     
    public String obtenerVP(JComboBox cmbEstado,JComboBox cmbEstado2){
    String resultado="";
     int valor= obtenerIdTipoUsr(tipousuario);
      int valor2=obtenerIdModulo(modulo);
    
    try {
            
            Statement statement = cn.createStatement();
            ResultSet obtenerAP = statement.executeQuery(" SELECT Visualizar_Priv FROM Privilegios INNER JOIN Tipo_Usr on Privilegios.Tipo_Usr_idTipo_Usr = Tipo_Usr.idTipo_Usr where Tipo_Usr_idTipo_Usr = '"+valor+"'  and Modulo_idModulo= '"+valor2+"' ");
            while (obtenerAP.next()) {
                resultado=obtenerAP.getString(1);
            }//FIN WHILE
            
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    return resultado;
}
     
 

 //Update
    public void Update(JComboBox agregar ,JComboBox borrar,JComboBox actualizar,JComboBox ver){
   /* int a,b,ac,v;
    int a = agregar.getSelectedIndex();*/


        int a = agregar.getSelectedIndex();
        int b = borrar.getSelectedIndex();
        int ac= actualizar.getSelectedIndex();
        int v= ver.getSelectedIndex();
        String as= "",bs="",acs="",vs="";
        
        if(a==1){
            as="S";
        }else{as="N";}
        
        if(b==1){
            bs="S";
        }else{bs="N";}
        
        if(ac==1){
            acs="S";
        }else{acs="N";}
        
        if(v==1){
            vs="S";
        }else{vs="N";}
        
  


   
   
     int valor= obtenerIdTipoUsr(tipousuario);
     int valor2=obtenerIdModulo(modulo);
    
    try {
            
            Statement statement = cn.createStatement();
            statement.executeUpdate(" UPDATE Privilegios SET Agregar_Priv = '"+as+"' , Borrar_Priv = '"+bs+"' , Actualizar_Priv = '"+acs+"' ,Visualizar_Priv= '"+vs+"' WHERE Tipo_Usr_idTipo_Usr = '"+valor+"' and Modulo_idModulo = '"+valor2+"'");
           
            
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    
}



    
     
     
   //asta aqui
   
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Update( agregar ,borrar,actualizar, ver);
      
        
        int a=tipousuario.getSelectedIndex();
        int b=modulo.getSelectedIndex();
        if(a==0 ){JOptionPane.showMessageDialog(null,"Seleccione el tipo de usuario");}
        else if(b==0){JOptionPane.showMessageDialog(null,"Seleccione el modulo");}
        else{  JOptionPane.showMessageDialog(null,"Se modificaron los permisos");}
        
        
        
 
        
        

    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tipousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipousuarioActionPerformed
     



// TODO add your handling code here:
    }//GEN-LAST:event_tipousuarioActionPerformed

    private void tipousuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipousuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tipousuarioMouseClicked

    private void moduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloActionPerformed
String  obtenerAP= obtenerAP(tipousuario,modulo);
String  obtenerBP= obtenerBP(tipousuario,modulo);
String  obtenerAcP= obtenerAcP(tipousuario,modulo);
String  obtenervP= obtenerVP(tipousuario,modulo);
 

if(modulo.getSelectedItem().equals("Solicitudes")){
if(obtenerAP.equals("S")){
agregar.setSelectedIndex(1);

}  else {agregar.setSelectedIndex(0);}  
borrar.setEnabled(false);
actualizar.setEnabled(false);
ver.setEnabled(false);
jLabel2.setText("Agregar Modulo");


} 

if (!modulo.getSelectedItem().equals("Solicitudes")){

if(obtenerAP.equals("S")){
agregar.setSelectedIndex(1);

}  else {agregar.setSelectedIndex(0);}  

if(obtenerBP.equals("S")){
borrar.setSelectedIndex(1);
}else {borrar.setSelectedIndex(0);}  

if(obtenerAcP.equals("S")){
    actualizar.setSelectedIndex(1);}
else {actualizar.setSelectedIndex(0);} 

if(obtenervP.equals("S")){
ver.setSelectedIndex(1);
}else {ver.setSelectedIndex(0);} 

borrar.setEnabled(true);
actualizar.setEnabled(true);
ver.setEnabled(true);
jLabel2.setText("Agregar");

}
        // TODO add your handling code here:
    }//GEN-LAST:event_moduloActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

 dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsigPrivi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsigPrivi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsigPrivi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsigPrivi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsigPrivi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> actualizar;
    private javax.swing.JComboBox<String> agregar;
    private javax.swing.JComboBox<String> borrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> modulo;
    private javax.swing.JComboBox<String> tipousuario;
    private javax.swing.JComboBox<String> ver;
    // End of variables declaration//GEN-END:variables
}
