
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;


public class Consulta extends javax.swing.JDialog {
    
    String query;
    Datos_Solicitud ds;
        
    public Consulta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        query = "SELECT CONCAT(Nombre_Per,' ',Ape_Pat_Per,' ',Ape_Mat_Per) AS Nombre, Nom_Pues, RFC_Emp FROM Persona"
                        + " INNER JOIN Empleado e ON idPersona = e.Persona_idPersona"
                        + " INNER JOIN Puestos p ON e.Puestos_idPuesto = p.idPuesto"
                        + " WHERE CONCAT(Nombre_Per,' ',Ape_Pat_Per,' ',Ape_Mat_Per) LIKE \'%";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCosulta = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtbCosulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numbre Completo.", "Puesto.", "RFC."
            }
        ));
        jtbCosulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbCosultaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbCosulta);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        jtbCosulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Numbre Completo.", "Puesto.", "RFC."}
        ));
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        try {
            Statement statement = cn.createStatement();
            ResultSet obtenerAP = statement.executeQuery(query+txtBuscar.getText().toUpperCase()+"%\';");
            
            int indiceReglon = 0;
            while (obtenerAP.next()) {
                DefaultTableModel temp = (DefaultTableModel) jtbCosulta.getModel();
                Object nuevo[]= {"","",""};
                temp.addRow(nuevo);
                
                jtbCosulta.setValueAt(obtenerAP.getString(1), indiceReglon, 0);
                jtbCosulta.setValueAt(obtenerAP.getString(2), indiceReglon, 1);
                jtbCosulta.setValueAt(obtenerAP.getString(3), indiceReglon, 2);
                indiceReglon++;
            }//FIN WHILE
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void jtbCosultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbCosultaMousePressed
    }//GEN-LAST:event_jtbCosultaMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jtbCosulta.getSelectedRows().length < 1){
            showMessageDialog(this, "Seleccionar solo un usuario,", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ds.btnDest.setText((String)jtbCosulta.getValueAt(jtbCosulta.getSelectedRow(), 2));
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbCosulta;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
